language: node_js
node_js:
  - "0.11"
service: postgresql
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y python3-dev python3-setuptools python-dev python-setuptools
- sudo easy_install-2.7 pip
- sudo pip2 install psycopg2
- sudo pip2 install htsql-pgsql
- sudo pip2 install supervisor
- sudo easy_install3 pip
- sudo pip3 install ddlgenerator
- psql -c 'create database codetalker;' -U postgres
- psql -f data/test_data_slice.sql -U postgres codetalker
- psql -c "select count(*) from code" -U postgres codetalker
- sudo cp config/htsql.conf /etc/init/
- sudo service htsql start
- sleep 5  # give HTSQL time to come online
- service htsql status
- curl "http://127.0.0.1:8080/meta(/table)/:json"
- npm install -g grunt-cli
- npm install -g bower
- npm install -g coffee-script
- npm install -g request
- gem install compass
- bower install
deploy:
  provider: opsworks
  access_key_id: AKIAJUWHVUZI4E4P7I4Q
  secret_access_key:
    secure: Tj+vfz6TiC+r4n1UkesiJXBn/n20NPZsUY84drS3iToT8zfQYcnpN8aBsHZ8JtZ4BAUWfvtz7OQFJHfPV49wvCNJ+GFHwJorVGqFG5wJthrjDZzOs1tNzO+Rd+VNczscIMNQeD0k1x6UKg6BjOndIO9gBqWKsW3kCbjsXtECr8o=
  app-id: e87e7fc2-d0cc-4f83-b1b4-369ed87c0f79 
  on:
    repo: 18F/codetalker
