language: node_js
node_js:
  - "0.11"
before_install: 
- npm install -g grunt-cli
- npm install -g bower
- gem install compass
- bower install
deploy:
  provider: opsworks
  access_key_id: AKIAJUWHVUZI4E4P7I4Q
  secret_access_key:
    secure: Tj+vfz6TiC+r4n1UkesiJXBn/n20NPZsUY84drS3iToT8zfQYcnpN8aBsHZ8JtZ4BAUWfvtz7OQFJHfPV49wvCNJ+GFHwJorVGqFG5wJthrjDZzOs1tNzO+Rd+VNczscIMNQeD0k1x6UKg6BjOndIO9gBqWKsW3kCbjsXtECr8o=
  app-id: e87e7fc2-d0cc-4f83-b1b4-369ed87c0f79 
  on:
    repo: 18F/codetalker
