# Configuration for librarian-puppet. For example:
#
forge "https://forgeapi.puppetlabs.com"

mod "puppetlabs/vcsrepo"
mod "puppetlabs/stdlib"
mod "willdurand/nodejs"
mod "maestrodev/puppet-wget",
    :git => "git://github.com/maestrodev/puppet-wget.git"
mod "puppetlabs/apt"
mod "saz/timezone"
